language: c

compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git

script:
    - export DS_KERNEL_PATH=linux-stable
    - make

notifications:
  email:
    on_success: change
    on_failure: always
