language: c

compiler: gcc

before_install:
    - sudo apt-get update -qq
    - git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git

install:
    - pushd .
    - cd $(pwd)/linux-stable && git checkout master && git pull && git checkout -b b4.4.13 v4.4.13 && make defconfig && make prepare && make modules_prepare
    - popd

script:
    - export KERNEL_BUILD_PATH=$(pwd)/linux-stable
    - make

notifications:
  email:
    on_success: change
    on_failure: always
