language: c

compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - mkdir linux-stable

script:
    - ls -al $(pwd)/linux-stable
    - export DS_KERNEL_PATH=$(pwd)/linux-stable
    - make

notifications:
  email:
    on_success: change
    on_failure: always
