language: c

compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - pwd

script:
    - pwd
    - export DS_KERNEL_PATH=linux-stable
    - make

notifications:
  email:
    on_success: change
    on_failure: always
