language: c

compiler: gcc

before_install:
    - sudo apt-get update -qq
    - git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git

install:
    - pushd .
    - cd $(pwd)/linux-stable && git checkout master && git pull && git checkout -b b3.17.3 v3.17.3
    - popd

script:
    - export DS_KERNEL_PATH=$(pwd)/linux-stable
    - make

notifications:
  email:
    on_success: change
    on_failure: always
