language: c

compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install linux-headers-$(uname -r)
    - sudo apt-get install make

script:
    - make

notifications:
  email:
    on_success: change
    on_failure: always
